/** @type {import('stylelint').Config} */
export default {
    extends: ['stylelint-config-standard-scss'],
    ignoreFiles: ['node_modules/**', 'dist/**', '_site/**', 'src/styles/_tokens.scss'],
    rules: {
        'alpha-value-notation': null,
        'at-rule-empty-line-before': null,
        'color-function-alias-notation': null,
        'color-function-notation': null,
        'color-hex-length': null,
        'comment-empty-line-before': null,
        'custom-property-empty-line-before': null,
        'declaration-empty-line-before': null,
        'media-feature-range-notation': null,
        'no-descending-specificity': null,
        'no-duplicate-selectors': null,
        'no-invalid-position-at-import-rule': null,
        'property-no-vendor-prefix': null,
        'rule-empty-line-before': null,
        'scss/dollar-variable-empty-line-before': null,
        'scss/dollar-variable-no-missing-interpolation': null,
        'scss/load-partial-extension': null,
        'scss/operator-no-newline-after': null,
        'scss/operator-no-unspaced': null,
        'selector-not-notation': null,
        'selector-pseudo-element-colon-notation': null,
        'value-keyword-case': null,
    },
};
